global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nginx-exporter'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['127.0.0.1:9113']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['127.0.0.1:9100']
